version: '3'

services:
  server:
    image: joeldotdias/gateg
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@squeel:3306/${MYSQL_DATABASE}
      - SOCKET_ADDR=0.0.0.0:6969
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '6969:6969'
    depends_on:
      - squeel
  
  squeel:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    ports:
      - '3376:3306'
    volumes:
      - mysqlDB:/var/lib/mysql

volumes:
  mysqlDB:
    driver: local
