spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateguardian?useSSL=false&serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update